# Model Setup

In [1]:
import numpy as np

### Getting the data

In [10]:
#Sample data
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])

In [11]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [12]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

## Model Building

### Training Data:
Data that our algorithm learns from to produce results(model)

Validation Data:
Data thatw e use to test our results(model) in the process of building our model.

Testing Data:
Data that we use to test our final results(model) that our algorithm had produced. 

### Splitting our data:

train_size : is the number that defines the size of the training set

test_size : is the number that defines the size of the test set(test_size=0.30).

random_state : is the object that controls randamization during splitting(random_state=1000). 

shuffle : is the Boolena object(True by default) that determines wheather to shuffle the dataser before applying the split

stratify : is an array-like object that, if not None, determines how to use a startified(destributes the y value equally between train and test data)

In [13]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30,random_state = 1000, stratify = y)

In [31]:
x_train

array([[17, 18],
       [11, 12],
       [21, 22],
       [ 7,  8],
       [15, 16],
       [23, 24],
       [ 9, 10],
       [19, 20]])

In [32]:
x_test

array([[ 1,  2],
       [13, 14],
       [ 5,  6],
       [ 3,  4]])

In [34]:
y_train

array([1, 0, 1, 0, 1, 0, 1, 0])